### ISSUE TITLE
env registration fails

### ISSUE THREAD

**Issue by hail-mary** [zichunxx/panda_mujoco_gym#2]
Hi, I've tried testing the "FrankaPickAndPlaceSparse-v0" environment with the following code.
```python
import sys
import time
import gymnasium as gym
import panda_mujoco_gym

if __name__ == "__main__":
    env = gym.make("FrankaPickAndPlaceSparse-v0", render_mode="human")

    observation, info = env.reset()

    for _ in range(1000):
        action = env.action_space.sample()
        observation, reward, terminated, truncated, info = env.step(action)

        if terminated or truncated:
            observation, info = env.reset()

        time.sleep(0.2)

    env.close()
```
However the process stops in line 7,
`env = gym.make("FrankaPickAndPlaceSparse-v0", render_mode="human")`
and I see error messages like this:
` line 121, in FrankaEnv
    def step(self, action) -> tuple[ObsType, SupportsFloat, bool, bool, dict[str, Any]]:
TypeError: 'type' object is not subscriptable`

I use slightly newer version of packages than specified in requiments.txt
mujoco==2.3.7
gymnasium==0.29.1
gymnasium-robotics==1.2.4
stable_baselines3==2.3.2

I've tried replacing line 7 as `env = gym.make('FrankaKitchen-v1', tasks_to_complete=['microwave', 'kettle'],
                   render_mode='human')
`.
This is one of the original gymnasium-robotics envs and it worked without any problem. Thus I inferred that my problem comes from registration failure.
How can I fix this? Thanks in advance.

**Comment by zichunxx** [comment]
Hi! @hail-mary Thanks for trying this repo.

This repo is constructed with python3.9. The problem you mentioned seems to be triggered by the unmatched `typing` version. 

You can delete the return annotation for simplicity or change `tuple` to `typing.Tuple`.

**Comment by hail-mary** [comment]
I changed my python version to 3.9 and it worked!
Thank you so much for your help!!
